# fly.toml app configuration file generated for planning-poker-vas6781 on 2024-04-22T20:24:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'planning-poker-app'
primary_region = 'gru'

[build]
  buildpacks = ['https://github.com/HashNuke/heroku-buildpack-elixir']

[env]
  PORT = '4000'
  RELEASE_COOKIE = "planning-poker"
  DNS_CLUSTER_QUERY = "planning-poker-app.internal"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
