apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planning-poker-ingress
  namespace: planning-poker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - planning.savioserra.dev
      secretName: planning-poker-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planning-poker
                port:
                  name: http
