apiVersion: v1
kind: Service
metadata:
  name: planning-poker
  namespace: planning-poker
spec:
  ports:
  - port: 80
    targetPort: 4000
  - port: 443
    targetPort: 4001
  selector:
    app: planning-poker